apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s-demo
  template:
    metadata:
      labels:
        app: spring-k8s-demo
    spec:
      containers:
        - name: spring-k8s-demo
          image: spring-k8s-demo
          imagePullPolicy: Never
          ports:
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-demo
spec:
  type: NodePort
  selector:
    app: spring-k8s-demo
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30001
